version: '3'

services:
  aw-acc-status:
    restart: always
    image: rsjorslev/aw-acc-status:latest
    container_name: aw-acc-status
    ports:
     - "8080:8080"
    volumes:
     - /etc/runner/config/props:/config
